### ISSUE TITLE
Improve reliability of FakeStripe::Utils.find_available_port

### ISSUE THREAD

**Issue by eliotsykes** [thoughtbot/fake_stripe#105]
Consider updating `FakeStripe::Utils.find_available_port` to reduce the likelihood of `Errno::EADDRINUSE` errors when the port was not released in time by the server used to find it. 

https://github.com/thoughtbot/fake_stripe/blob/618b77b67eaea32eae38c6347c92b426e0eecaf7/lib/fake_stripe/utils.rb#L7-L12

Consider borrowing from Capybara's recently tweaked port finding code to check the server was closed: 

https://github.com/teamcapybara/capybara/blob/6b2d6a1012138bf1230c0832dc17e36ea52a053a/lib/capybara/server.rb#L107-L122

Related discussion: https://github.com/teamcapybara/capybara/pull/2244

**Comment by stefannibrasil** [comment]
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154
