### ISSUE TITLE
react-stripe-js is unable to create individual elements

### ISSUE THREAD

**Issue by mpmenne** [thoughtbot/fake_stripe#115]
So we're using the [react-stripe-js](https://github.com/stripe/react-stripe-js) to render Stripe elements on the page.   When we render the Stripe elements using the JavaScript returned by the `STRIPE_JS_HOST/v3/`, it renders every component each time we call `create`.  Please check out the example below.

Here is a code example.
```
    this.stripe = Stripe(stripeApiKey);
    const elements = this.stripe.elements();

    this.cardNumber = elements.create('cardNumber', {
      placeholder: this.cardTarget.dataset.placeholder,
      style: this.style,
    });
    this.cardExpiry = elements.create('cardExpiry', {
      placeholder: this.dateTarget.dataset.placeholder,
      style: this.style,
    });
    this.cardCvc = elements.create('cardCvc', {
      placeholder: this.cvcTarget.dataset.placeholder,
      style: this.style,
    });
    this.postalCode = elements.create('postalCode', {
      placeholder: this.postalCodeTarget.dataset.placeholder,
      style: this.style,
    });
```  
### Expected Result ### 
<img width="549" alt="Screen Shot 2020-04-14 at 4 58 57 PM" src="https://user-images.githubusercontent.com/217904/79278647-b87faa00-7e71-11ea-8b31-3971bcfed822.png">

### Actual Result ### 
<img width="498" alt="Screen Shot 2020-04-14 at 4 58 46 PM" src="https://user-images.githubusercontent.com/217904/79278654-bddcf480-7e71-11ea-9956-9df9ef15511a.png">

It looks like we have the parameters, we just need to dynamically render the correct fields:
https://github.com/thoughtbot/fake_stripe/blob/master/lib/fake_stripe/assets/v3.js#L24

Happy to submit a PR if other people are seeing this issue as well.

**Comment by mpmenne** [comment]
Submitted PR #116  to address this issue.  Please take a look and let me know if you have any feedback!

**Comment by stefannibrasil** [comment]
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154
