### ISSUE TITLE
Add API stub for products 

### ISSUE THREAD

**Issue by cgruppioni** [thoughtbot/fake_stripe#120]
**Product documentation:** https://stripe.com/docs/api/products
**Stub file:** https://github.com/thoughtbot/fake_stripe/blob/e6784a490f00478a9047f2a7ac5da7381d9a8e97/lib/fake_stripe/stub_app.rb

**Comment by stefannibrasil** [comment]
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154
