### ISSUE TITLE
Supporting `paymentRequest` and `createPaymentMethod`

### ISSUE THREAD

**Issue by basicallydan** [thoughtbot/fake_stripe#152]
Hey there! Thanks for making this wonderful gem.

I've already started working on a fork which would support the `paymentRequest` and `createPaymentMethod` functions on the `stripe` object, but I thought I should just check before I get too deep to see if this is something someone has already done or maybe has started on their own fork. And also gather some interest in case, if I do finish, I know whether to make a PR or not.

Thanks!

**Comment by stefannibrasil** [comment]
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154
