### ISSUE TITLE
Validate inputs to charge

### ISSUE THREAD

**Issue by derekprior** [thoughtbot/fake_stripe#19]
Fake stripe should validate the inputs to charge similarly to Stripe and should raise the same errors if appropriate.

For instance, raise if there is no token. Raise if amount is not a positive integer. Raise if there's no currency, etc.

**Comment by stefannibrasil** [comment]
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154
