### ISSUE TITLE
Customer data in fixture files

### ISSUE THREAD

**Issue by harlow** [thoughtbot/fake_stripe#25]
Lauren Lusher from Stripe reached out to me via email asking to remove <REDACTED> personal email address from the example payloads. It looks like some customer data leaked into the codebase with this commit:

https://github.com/thoughtbot/fake_stripe/commit/f2ae5385497dfc02a925bd5d3f4259fbf6b3580f

We should cut a new version of this gem with all test data sanitized and yank the pervious versions from Ruby Gems. I'm wondering if its also worth squashing those commits out of git history?

cc @jferris @adarsh @cpytel 

Original email from Lauren (I'm not sure how it got on Omniref... do they just scrape Rubygems?)

```
Hi Harlow,

I work with Stripe and I'm reaching out about the fake_stripe gem you created on Omniref. Sorry to reach out to you out of the blue like this. One of our users got in touch with us recently, as he found that his personal email address was being used in some of your example documentation, pulled from Stripe's API docs:

<REDACTED>

It's become evident that the user didn't realize he was using Stripe's public test API keys to create test charges, and that the information would be publicly available later on. We use test data from the account associated with our test API key to populate Stripe's documentation. The data displayed is chosen at random, and unfortunately the test charges and customer objects he created were displayed when you copied our documentation. 

I'm wondering if it would be possible for you to use different examples on Omniref. We are working on improving this flow and have removed all instances of the email address from the account, and I believe it would put the developer's mind at ease to see his personal email address removed from Omniref. 

Look forward to hearing from you.

Best,
Lauren
```

**Comment by rfauver** [comment]
@harlow @adarsh @jsteiner Looks like this never got removed from the git history, was that supposed to happen at some point?

**Comment by adarsh** [comment]
Will have to leave this for @jsteiner - I no longer have permissions on this repo.

**Comment by kaoru** [comment]
Came to say this ⏫ 

> Looks like this never got removed from the git history

https://github.com/thoughtbot/fake_stripe/commit/74ceb6d6f2ac7ca04daedcefdef247241eee868b

I wonder how many commits with messages like "Remove sensitive user data" there are on Github 😓
