### ISSUE TITLE
AuthenticationError

### ISSUE THREAD

**Issue by JamesChevalier** [thoughtbot/fake_stripe#43]
I'm not sure what I'm doing wrong... Do you have any ideas/suggestions based on my experiences, below?

I've got an API-only Rails app that is integrated with Stripe. My spec has this line in it:

    stripe_customer = Stripe::Customer.create

which causes this error:

```
1) Subscription is created in Stripe
   Failure/Error: stripe_customer = Stripe::Customer.create

   Stripe::AuthenticationError:
     Invalid API Key provided: ****_******_***_KEY
   # /Users/me/.rvm/gems/ruby-2.3.0@project/gems/stripe-1.43.1/lib/stripe.rb:333:in `handle_api_error'
   # /Users/me/.rvm/gems/ruby-2.3.0@project/gems/stripe-1.43.1/lib/stripe.rb:209:in `rescue in execute_request_with_rescues'
   # /Users/me/.rvm/gems/ruby-2.3.0@project/gems/stripe-1.43.1/lib/stripe.rb:195:in `execute_request_with_rescues'
   # /Users/me/.rvm/gems/ruby-2.3.0@project/gems/stripe-1.43.1/lib/stripe.rb:148:in `request'
   # /Users/me/.rvm/gems/ruby-2.3.0@project/gems/stripe-1.43.1/lib/stripe/api_operations/request.rb:15:in `request'
   # /Users/me/.rvm/gems/ruby-2.3.0@project/gems/stripe-1.43.1/lib/stripe/api_operations/create.rb:5:in `create'
   # ./spec/models/subscription_spec.rb:69:in `block (3 levels) in <top (required)>'
   # ------------------
   # --- Caused by: ---
   # RestClient::Unauthorized:
   #   401 Unauthorized
   #   /Users/me/.rvm/gems/ruby-2.3.0@project/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
```

I did some searching around GitHub to see how others are using FakeStripe, and I came across [this method](https://github.com/codecation/trailmix/blob/123ff106a0e6a41c223755cf5b9c1273ea4847fe/spec/controllers/subscriptions_controller_spec.rb#L76-L80) which suggests to me that I still need to write all my own `allow` calls. I'm not sure if that's correct, though.

**Comment by swanson** [comment]
I ran into the same issue. I added the following to my spec_helper:

```ruby
require "webmock/rspec"
WebMock.disable_net_connect!(allow_localhost: true)
```

I'm not entirely sure *why* that fixes it, but that seemed to do the trick.

**Comment by swanson** [comment]
It seems like `suspenders` includes this WebMock configuration in the default spec_helper, so maybe this needs to be added to the documentation for general usage?

**Comment by mrgilman** [comment]
@JamesChevalier: You shouldn't have to write your own `allow` calls. I was able to reproduce this, and can confirm that @swanson's solution works. I am curious why this is necessary, as WebMock is a dependency of fake_stripe, and [this initializer](https://github.com/thoughtbot/fake_stripe/blob/master/lib/fake_stripe/initializers/webmock.rb) has almost the exact same code. I am looking into it.

Thanks!
