### ISSUE TITLE
Redefine dependency on `stripe` gem

### ISSUE THREAD

**Issue by cllns** [thoughtbot/fake_stripe#56]
Right now the `stripe` gem is [listed as a development dependency](https://github.com/thoughtbot/fake_stripe/blob/master/fake_stripe.gemspec#L21).

But it's actually a run-time dependency, since the instructions say to [set `Stripe.api_key`](https://github.com/thoughtbot/fake_stripe/blame/master/README.md#L30) and the Stripe constant is not defined (without adding the Stripe gem to my Gemfile).

It might be possible to remove the dependency on Stripe, I'm not sure.

(I'm using _only_ Stripe.js, not the `stripe` gem, which is how I found this)

**Comment by cllns** [comment]
Also, the README will need to be updated, I think, to put `fake_stripe` in both `:test` and `:development` environments.

**Comment by stefannibrasil** [comment]
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154
