### ISSUE TITLE
No support for Js v3

### ISSUE THREAD

**Issue by caherrerapa** [thoughtbot/fake_stripe#70]
This gem is great, thanks for contributing. Currently Stripe offers v3 API and would be nice to have it here too

**Comment by caseyprovost** [comment]
+1 There seem to be no resources for testing against Stripe elements with RSpec either. This is awful cause I don't have a path to fix integration tests after migrating from Braintree :(

**Comment by wxmn** [comment]
Any plans on adding support for v3? Any technical hurdles that are blocking it? For instance, is it harder to mock the new Elements feature?

**Comment by sublimecoder** [comment]
V3 support would be awesome! Any movement on this front?

**Comment by danbee** [comment]
I've just opened a PR for basic Elements support here https://github.com/thoughtbot/fake_stripe/pull/91

**Comment by DylanReile** [comment]
@danbee Thanks for your PR adding basic Elements support. We're looking at extending it to support `card.addEventListener` and specific responses corresponding to the different Stripe testing numbers.  Have you ran into the need for that functionality yourself?

**Comment by stefannibrasil** [comment]
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154
