### ISSUE TITLE
Setting Coupon Duration

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/fake_stripe#72]
When I tried to set the coupon duration, it's always coming back as "forever" when I run the model specs. It seems to be because the json response is preset.

https://github.com/thoughtbot/fake_stripe/blob/9f2e58a131dbb7f28a1d289c31297580ac04365e/lib/fake_stripe/fixtures/list_coupons.json

**Comment by ACPK** [comment]
https://github.com/thoughtbot/fake_stripe/pull/74

**Comment by stefannibrasil** [comment]
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154
