### ISSUE TITLE
No tests for coupon "amount_off"

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/fake_stripe#73]
All of the sample JSON responses have percent_off set and amount_off equal to nil.

https://github.com/thoughtbot/fake_stripe/blob/9f2e58a131dbb7f28a1d289c31297580ac04365e/lib/fake_stripe/fixtures/list_coupons.json

**Comment by ACPK** [comment]
Pull Request: #74

**Comment by stefannibrasil** [comment]
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154
