### ISSUE TITLE
Testing Incorrect Coupon Codes

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/fake_stripe#75]
How would I tests incorrect coupon codes in the controller? When I use, "Stripe::Coupon.retrieve("dajkfjkadfjkadfakdfkjadjkfjkadf")", it goes back as a valid coupon with the id of "25OFF"?

    context "with invalid coupon" do
      it "should not set a coupon in session" do
        get :show, id: "1OFF"

        expect(session[:coupon]).to be_nil
        expect(flash[:error]).to eq I18n.t("coupons.flashes.invalid")
        expect(response).to redirect_to(root_path)
      end
    end

**Comment by srt32** [comment]
The library always returns success right now. Coupon retrieval happens in https://github.com/thoughtbot/fake_stripe/blob/master/lib/fake_stripe/stub_app.rb#L170. I think an update to the library would be needed to allow for faking failures / not founds.

**Comment by stefannibrasil** [comment]
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154
