### ISSUE TITLE
Leverage the Stripe Gems test data

### ISSUE THREAD

**Issue by harlow** [thoughtbot/fake_stripe#8]
Looks like a lot of the responses are already stubbed out in the official Stripe Gem. See if we can leverage those. It would probably help avoid API drift as the Stripe Gem would also need to update if the Stripe API ever changes.

**Comment by mcmire** [comment]
Sorry to dredge this up, but I hadn't heard of stripe-ruby-mock before, and I just tried it out. It seems to include a lot more functionality than fake_stripe, so on first glance, it would seem like a better project, but I failed to notice that it doesn't stub Stripe.js like fake_stripe does. 

Still, if the code here was added to stripe-ruby-mock, then we'd really have a great solution to stubbing Stripe completely.

**Comment by stefannibrasil** [comment]
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154
