### ISSUE TITLE
TRAVIS issue only

### ISSUE THREAD

**Issue by fringify** [thoughtbot/fake_stripe#80]
I have below error on my travis server. It's fine on my local.
NoMethodError: undefined method `closed?' for nil:NilClass

the code that reports is something like this.

```
FakeStripe.stub_stripe
Stripe::Token.create(last4: "9191", exp_year: 1984).id

```

**Comment by srt32** [comment]
Does your code call `closed?` on a Stripe object (perhaps on an [invoice](https://github.com/thoughtbot/fake_stripe/blob/master/lib/fake_stripe/fixtures/create_invoice.json#L36)?)?

Can you confirm you have the same environment / config set up on Travis as you do locally?

**Comment by stefannibrasil** [comment]
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154
