### ISSUE TITLE
Stripe Customer retrieve stub and expand default_source option

### ISSUE THREAD

**Issue by eliotsykes** [thoughtbot/fake_stripe#85]
The customer retrieve stub currently doesn't support Stripe's `expand: ['default_source']` option:

```rb
customer = Stripe::Customer.retrieve(id: 'customer-id-here', expand: ['default_source'])
```

With fake_stripe and Stripe `customer = Stripe::Customer.retrieve(id: 'customer-id-here')` (no expand option) the `customer.default_source` returns a String (the id of the default payment source).

However with Stripe, but not fake_stripe `customer = Stripe::Customer.retrieve(id: 'customer-id-here', expand: ['default_source])` (note the expand option) the `customer.default_source` returns the populated payment source object (not just the string id of the payment source). fake_stripe only returns the String id of the payment source.

(stripe-ruby-mock has a similar issue that may be useful https://github.com/rebelidealist/stripe-ruby-mock/issues/109 )

**Comment by stefannibrasil** [comment]
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154
