### ISSUE TITLE
Using with Stripe checkout

### ISSUE THREAD

**Issue by staycreativedesign** [thoughtbot/fake_stripe#92]
Does this work with stripe checkout?? The response I get from fake_strip is totally broken... I check the network log and I see tokens and everything but it doesnt work at at...

https://gist.github.com/staycreativedesign/b11347d002f6cbc2f06af616fe806e98

What can I be missing?

**Comment by stefannibrasil** [comment]
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154
