### ISSUE TITLE
Sinatra endpoints always return the same UUIDs

### ISSUE THREAD

**Issue by LilyReile** [thoughtbot/fake_stripe#94]
Hi, I ran into this problem while writing a system test for a feature that issues multiple Stripe transactions. Post submission, we save the returned transaction_ids to a column with a unique index. Since the `create_transaction` fixture returned by stub_app always returns the same UUID, this throws an error on the second transaction submission.

Would it be problematic to return a random UUID instead?

**Comment by stefannibrasil** [comment]
Closing this because fake_stripe has been deprecated: https://github.com/thoughtbot/fake_stripe/pull/154
